---
- name: Establish and hold Rosenpass connection on the servers
  hosts: sender

  tasks:
  - name: Build and keep connection
    shell:
      cmd: rp exchange "rp-keys/{{ inventory_hostname }}.rosenpass-secret" dev rosenpass0 listen {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:9999 peer "rp-keys/{{ hostvars[item]['inventory_hostname'] }}.rosenpass-public" allowed-ips fe80::/64
    with_items: "{{ groups['receiver'] }}"
    become: true
    become_user: root